import { describe, it, expect, beforeEach } from 'vitest';
import { Command } from 'commander';
import { mkdtempSync, readdirSync, existsSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { registerPacks } from '../src/commands/packs.js';
import { PACK_INDEX } from '../src/pack-index.js';
import { packFileUrl, type PackFetcher } from '../src/commands/packs-fetch.js';

const PACKS_DIR = fileURLToPath(new URL('../../packs/packs', import.meta.url));

const run = async (args: string[], fetcher: PackFetcher): Promise<string> => {
	const out: string[] = [];
	const p = new Command('integration-mock').exitOverride();
	registerPacks(p, { write: (s) => out.push(s) }, fetcher);
	await p.parseAsync(['node', 'integration-mock', ...args]);
	return out.join('\n');
};

/** Serves the real pack content from disk, so tests exercise real files. */
const fromDisk: PackFetcher = async (url) => {
	const m = /packages\/packs\/packs\/(.+)$/.exec(url);
	const { readFile } = await import('node:fs/promises');
	return readFile(join(PACKS_DIR, m![1]!), 'utf8');
};

beforeEach(() => {
	process.env.INTEGRATION_MOCK_HOME = mkdtempSync(join(tmpdir(), 'home-'));
	process.chdir(mkdtempSync(join(tmpdir(), 'proj-')));
});

describe('pack index', () => {
	it('lists exactly the packs that exist on disk', async () => {
		// Generated by build-index.mjs. Without this it drifts silently, and
		// `packs install` starts offering things that are not there.
		const onDisk = (await readdir(PACKS_DIR, { withFileTypes: true }))
			.filter((e) => e.isDirectory())
			.map((e) => e.name)
			.sort();
		expect(Object.keys(PACK_INDEX).sort()).toEqual(onDisk);
	});

	it('records the files each pack is made of', () => {
		for (const [id, e] of Object.entries(PACK_INDEX)) {
			expect(e.files, id).toContain('pack.json');
			expect(e.bytes, id).toBeGreaterThan(0);
		}
	});
});

describe('packs list', () => {
	it('accounts for every pack in the index, and never fetches', async () => {
		// In this workspace the library layer holds all 26 packs, so none are
		// "available" — that row only appears in a published install, which ships
		// the core set alone. What holds in BOTH is that every indexed pack is
		// accounted for exactly once. The available path itself is verified
		// against a real tarball, where the condition actually arises.
		const out = await run(['packs', 'list'], () => {
			throw new Error('list must not fetch');
		});
		for (const id of Object.keys(PACK_INDEX)) {
			expect(out, id).toMatch(new RegExp(`^${id}\\t`, 'm'));
		}
	});

	it('--installed never shows an available row', async () => {
		const out = await run(['packs', 'list', '--installed'], () => {
			throw new Error('no fetch');
		});
		expect(out).not.toMatch(/\tavailable\t/);
	});
});

describe('packs install', () => {
	it('downloads a pack and validates what arrived', async () => {
		const out = await run(['packs', 'install', 'stripe'], fromDisk);
		expect(out).toMatch(/installed stripe/);
		expect(existsSync(join(process.env.INTEGRATION_MOCK_HOME!, 'packs', 'stripe', 'pack.json'))).toBe(true);
	});

	it('refuses an id this release does not know', async () => {
		await expect(run(['packs', 'install', 'nope'], fromDisk)).rejects.toThrow(/no pack "nope"/);
	});

	it('does not silently replace an installed pack', async () => {
		await run(['packs', 'install', 'stripe'], fromDisk);
		expect(await run(['packs', 'install', 'stripe'], fromDisk)).toMatch(/already installed/);
	});

	it('removes a download that fails validation rather than serving it', async () => {
		const corrupt: PackFetcher = async (url) =>
			url.endsWith('pack.json')
				? JSON.stringify({ id: 'stripe', domains: [], prefix: 'no-leading-slash', source: 'openapi' })
				: fromDisk(url);
		await expect(run(['packs', 'install', 'stripe', '--no-verify'], corrupt)).rejects.toThrow(/failed validation/);
		expect(existsSync(join(process.env.INTEGRATION_MOCK_HOME!, 'packs', 'stripe'))).toBe(false);
	});

	it('checks every file against the release index and removes a download that differs', async () => {
		const tampered: PackFetcher = async (url) => {
			const body = await fromDisk(url);
			return url.endsWith('.json') && !url.endsWith('pack.json') ? body.replace('[', '[{"id":"evil","match":{"method":"GET","path":"/x"}},') : body;
		};
		await expect(run(['packs', 'install', 'stripe'], tampered)).rejects.toThrow(/does not match this release's index.*sha256/s);
		expect(existsSync(join(process.env.INTEGRATION_MOCK_HOME!, 'packs', 'stripe'))).toBe(false);
		expect(await run(['packs', 'install', 'stripe'], fromDisk)).toMatch(/sha256 verified/);
	});

	it('another ref is installed unverified, and says so', async () => {
		const out = await run(['packs', 'install', 'stripe', '--ref', 'main'], fromDisk);
		expect(out).toMatch(/not verified: --ref main/);
	});

	it('INTEGRATION_MOCK_PACK_INDEX_URL points install at a mirror', async () => {
		process.env.INTEGRATION_MOCK_PACK_INDEX_URL = 'https://packs.example.test/mirror/';
		try {
			expect(packFileUrl('v1.2.3', 'stripe', 'pack.json')).toBe('https://packs.example.test/mirror/stripe/pack.json');
			const seen: string[] = [];
			const mirror: PackFetcher = async (url) => {
				seen.push(url);
				return fromDisk(url.replace('https://packs.example.test/mirror', 'x/packages/packs/packs'));
			};
			expect(await run(['packs', 'install', 'stripe'], mirror)).toMatch(/sha256 verified/);
			expect(seen[0]).toMatch(/^https:\/\/packs\.example\.test\/mirror\/stripe\//);
		} finally {
			delete process.env.INTEGRATION_MOCK_PACK_INDEX_URL;
		}
	});

	it('builds the documented URL shape', () => {
		expect(packFileUrl('v1.2.3', 'stripe', 'routes/00-generated.json')).toBe(
			'https://raw.githubusercontent.com/LudwigGerdes/integration-mock/v1.2.3/packages/packs/packs/stripe/routes/00-generated.json',
		);
	});
});
