/**
 * Generated by build-index.mjs — do not edit. Run `pnpm --filter integration-mock run index`.
 *
 * Every pack this release can install, so `packs list` can show what exists
 * without a network call. Only the core set ships inside the tarball; the rest
 * are fetched on demand by `packs install`.
 */
export interface PackIndexEntry {
	domains: string[];
	prefix: string;
	bytes: number;
	files: string[];
}

export const PACK_INDEX: Record<string, PackIndexEntry> = {
		"asana": {
			"domains": [
				"app.asana.com"
			],
			"prefix": "/asana",
			"bytes": 132606,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"clickup": {
			"domains": [
				"polls.apiblueprint.org"
			],
			"prefix": "/clickup",
			"bytes": 1485,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"close": {
			"domains": [
				"api.close.com"
			],
			"prefix": "/close",
			"bytes": 464654,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"datadog": {
			"domains": [
				"{subdomain}.{site}"
			],
			"prefix": "/datadog",
			"bytes": 1113849,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"generic-rest": {
			"domains": [],
			"prefix": "/generic-rest",
			"bytes": 447,
			"files": [
				"pack.json",
				"routes/00-overrides.json"
			]
		},
		"github": {
			"domains": [
				"api.github.com"
			],
			"prefix": "/github",
			"bytes": 2888388,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"gitlab": {
			"domains": [
				"gitlab.com"
			],
			"prefix": "/gitlab",
			"bytes": 257415,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"gmail": {
			"domains": [
				"gmail.googleapis.com"
			],
			"prefix": "/gmail",
			"bytes": 47131,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"google-drive": {
			"domains": [
				"www.googleapis.com"
			],
			"prefix": "/google-drive",
			"bytes": 91372,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"google-sheets": {
			"domains": [
				"sheets.googleapis.com"
			],
			"prefix": "/google-sheets",
			"bytes": 48178,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"hubspot": {
			"domains": [
				"api.hubapi.com"
			],
			"prefix": "/hubspot",
			"bytes": 29303,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"intercom": {
			"domains": [
				"api.intercom.io",
				"api.eu.intercom.io",
				"api.au.intercom.io"
			],
			"prefix": "/intercom",
			"bytes": 251946,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"jira": {
			"domains": [
				"your-domain.atlassian.net"
			],
			"prefix": "/jira",
			"bytes": 365802,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"microsoft-graph": {
			"domains": [
				"graph.microsoft.com"
			],
			"prefix": "/microsoft-graph",
			"bytes": 766662,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"notion": {
			"domains": [
				"api.notion.com"
			],
			"prefix": "/notion",
			"bytes": 87444,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"openai": {
			"domains": [
				"api.openai.com"
			],
			"prefix": "/openai",
			"bytes": 8091,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"pagerduty": {
			"domains": [
				"api.pagerduty.com"
			],
			"prefix": "/pagerduty",
			"bytes": 472550,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"pandadoc": {
			"domains": [
				"api.pandadoc.com"
			],
			"prefix": "/pandadoc",
			"bytes": 101836,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"pipedrive": {
			"domains": [
				"api.pipedrive.com"
			],
			"prefix": "/pipedrive",
			"bytes": 249447,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"salesforce": {
			"domains": [
				"*.my.salesforce.com",
				"login.salesforce.com",
				"test.salesforce.com"
			],
			"prefix": "/salesforce",
			"bytes": 6635,
			"files": [
				"pack.json",
				"routes/main.json"
			]
		},
		"sendgrid": {
			"domains": [
				"api.sendgrid.com"
			],
			"prefix": "/sendgrid",
			"bytes": 327598,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"slack": {
			"domains": [
				"slack.com"
			],
			"prefix": "/slack",
			"bytes": 107190,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"snowflake": {
			"domains": [
				"org-account.snowflakecomputing.com"
			],
			"prefix": "/snowflake",
			"bytes": 7196,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"stripe": {
			"domains": [
				"api.stripe.com"
			],
			"prefix": "/stripe",
			"bytes": 1262908,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"twilio": {
			"domains": [
				"api.twilio.com"
			],
			"prefix": "/twilio",
			"bytes": 157099,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		},
		"xero": {
			"domains": [
				"api.xero.com"
			],
			"prefix": "/xero",
			"bytes": 278985,
			"files": [
				"pack.json",
				"routes/10-generated.json"
			]
		}
	};
