import { createHash } from 'node:crypto';
import { readdir, stat, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * The catalogue of every pack this release can install.
 *
 * Emitted as a TypeScript module rather than a JSON file the CLI reads at
 * runtime: `packs list` must work offline and the bundle has no reliable path
 * back to its own package directory. Generated, with a test asserting it still
 * matches the packs on disk, so it cannot quietly go stale.
 */
const root = new URL('../../', import.meta.url).pathname;
const packsDir = join(root, 'packages/packs/packs');

const walk = async (dir, prefix = '') => {
	const out = [];
	for (const e of await readdir(dir, { withFileTypes: true })) {
		const rel = prefix === '' ? e.name : `${prefix}/${e.name}`;
		if (e.isDirectory()) out.push(...(await walk(join(dir, e.name), rel)));
		else out.push(rel);
	}
	return out.sort();
};

const entries = {};
for (const id of (await readdir(packsDir)).sort()) {
	const dir = join(packsDir, id);
	if (!(await stat(dir)).isDirectory()) continue;
	const files = await walk(dir);
	let bytes = 0;
	const sha256 = {};
	for (const f of files) {
		const content = await readFile(join(dir, f));
		bytes += content.length;
		sha256[f] = createHash('sha256').update(content).digest('hex');
	}
	const meta = JSON.parse(await readFile(join(dir, 'pack.json'), 'utf8'));
	entries[id] = {
		domains: meta.domains ?? [],
		prefix: meta.prefix,
		bytes,
		files,
		sha256,
		...(meta.version === undefined ? {} : { version: meta.version }),
		...(meta.owner === undefined ? {} : { owner: meta.owner }),
	};
}

const body = JSON.stringify(entries, null, '\t').replace(/\n/g, '\n\t');
await writeFile(
	join(root, 'packages/cli/src/pack-index.ts'),
	`/**
 * Generated by build-index.mjs — do not edit. Run \`pnpm --filter integration-mock run index\`.
 *
 * Every pack this release can install, so \`packs list\` can show what exists
 * without a network call. Only the core set ships inside the tarball; the rest
 * are fetched on demand by \`packs install\`.
 */
export interface PackIndexEntry {
	domains: string[];
	prefix: string;
	bytes: number;
	files: string[];
	/** sha256 of each file as this release shipped it; \`packs install\` checks downloads against it. */
	sha256: Record<string, string>;
	version?: string;
	owner?: string;
}

export const PACK_INDEX: Record<string, PackIndexEntry> = ${body};
`,
);
console.log(`pack index: ${Object.keys(entries).length} packs`);
